### ISSUE TITLE
Sign In email verification

### ISSUE THREAD

**Issue by skystar-p** [swsnu/swpp17-team2#54]
이메일로 인증하는 수단을 만들어야 한다.

- [x] 메일 서버 세팅하기
- [x] 백엔드 구현
- [x] 프론트엔드 구현

**Comment by skystar-p** [comment]
@tirr-c 예전에 메일 서버 있다고 했는데 그거 슬슬 만져야 할 거 같음

**Comment by tirr-c** [comment]
계정 하나 세팅했는데 진짜 작동하는지 확인이 필요함

**Comment by skystar-p** [comment]
ㅇㅋ 내일 함 해보자

**Comment by skystar-p** [comment]
링크를 클릭했을 때 "확인되었습니다!" 라는 메세지를 백엔드 측에서 넘겨줄지 아니면 따로 프론트에서 리퀘스트를 날려서 받아올지 결정이 필요함

**Comment by skystar-p** [comment]
Done!
