### ISSUE TITLE
Prepare production configuration

### ISSUE THREAD

**Issue by tirr-c** [swsnu/swpp17-team2#64]

**Comment by skystar-p** [comment]
`asgi.py`도 만들어야 하고 실제로 worker들이 잘 channel 별로 일을 나눠서 하는지 테스트도 해봐야 함

postgresql로도 바꾸고, redis 세팅도 끝내고, redis를 channels랑 연결하고 cache랑도 연결해야 한다

**Comment by tirr-c** [comment]
프로덕션 돌아가는 중
