### ISSUE TITLE
Static file serving strategy

### ISSUE THREAD

**Issue by skystar-p** [swsnu/swpp17-team2#70]
지금 #69 로 인해서 스태틱 파일을 장고가 그대로 서빙하는데, 이건 퍼포먼스에 별로 안 좋을 수 있음...

그래서 나중에 production에서는 nginx로 서빙을 해야한다

https://docs.djangoproject.com/en/1.11/howto/static-files/deployment/

**Comment by tirr-c** [comment]
nginx로 서빙하고 있다!
